"""
Mesh connectivity and node coordinates for the Heterosis plate finite element.

Holds two parallel node arrays:
  node_coordinates / w_location_matrix (8×n_elem): Q8 serendipity nodes used for geometry
    mapping and transverse displacement w.
  theta_node_coordinates / theta_location_matrix (9×n_elem): Q9 Lagrangian nodes used for
    rotations θ_x and θ_y. The first 8 rows are identical to w_location_matrix; row 9 holds
    one element-center node per element, auto-generated by from_arrays.

Every element, assembly, and boundary-condition routine receives a HeterosisMesh as its
geometric input.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class HeterosisMesh:
    """
    Node coordinates and element connectivity for the Heterosis element.

    Fields:
        node_coordinates:    (n_w_node, 2) physical (x, y) coordinates of all Q8 nodes.
        w_location_matrix:   (8, n_elem) global Q8 node indices per element, column-per-element.
        theta_node_coordinates: (n_theta_node, 2) physical (x, y) coordinates of all Q9 nodes.
                                 Rows 0..n_w_node-1 coincide with node_coordinates; remaining
                                 rows are element-center nodes appended by from_arrays.
        theta_location_matrix: (9, n_elem) global Q9 node indices per element, column-per-element.
    """

    node_coordinates: np.ndarray
    w_location_matrix: np.ndarray
    theta_node_coordinates: np.ndarray
    theta_location_matrix: np.ndarray

    @classmethod
    def from_arrays(
        cls,
        node_coordinates: np.ndarray,
        w_location_matrix: np.ndarray,
        theta_location_matrix: np.ndarray | None = None,
    ) -> "HeterosisMesh":
        """
        Construct a HeterosisMesh from Q8 connectivity, optionally with explicit Q9 connectivity.

        When theta_location_matrix is None, one center node is generated per element at the
        arithmetic mean of its eight Q8 node coordinates and appended to node_coordinates.
        These generated nodes are theta-only (no w DOF).
        """
        node_coordinates = np.asarray(node_coordinates, dtype=float)
        w_location_matrix = np.asarray(w_location_matrix, dtype=int)

        if node_coordinates.ndim != 2 or node_coordinates.shape[1] != 2:
            raise ValueError("node_coordinates must have shape (n_node, 2).")
        if w_location_matrix.ndim != 2 or w_location_matrix.shape[0] != 8:
            raise ValueError("w_location_matrix must have shape (8, n_element).")

        if theta_location_matrix is None:
            n_w_node = node_coordinates.shape[0]
            n_element = w_location_matrix.shape[1]

            center_coordinates = np.zeros((n_element, 2), dtype=float)
            generated_theta_location_matrix = np.zeros((9, n_element), dtype=int)
            generated_theta_location_matrix[:8, :] = w_location_matrix

            for element_id in range(n_element):
                geom_node_ids = w_location_matrix[:, element_id]
                center_coordinates[element_id, :] = node_coordinates[geom_node_ids, :].mean(axis=0)
                generated_theta_location_matrix[8, element_id] = n_w_node + element_id

            theta_node_coordinates = np.vstack([node_coordinates, center_coordinates])
            theta_location_matrix = generated_theta_location_matrix
        else:
            theta_location_matrix = np.asarray(theta_location_matrix, dtype=int)
            if theta_location_matrix.ndim != 2 or theta_location_matrix.shape[0] != 9:
                raise ValueError("theta_location_matrix must have shape (9, n_element).")
            theta_node_coordinates = node_coordinates.copy()

        return cls(
            node_coordinates=node_coordinates,
            w_location_matrix=w_location_matrix,
            theta_node_coordinates=theta_node_coordinates,
            theta_location_matrix=theta_location_matrix,
        )

    @property
    def total_w_node_number(self) -> int:
        return self.node_coordinates.shape[0]

    @property
    def total_theta_node_number(self) -> int:
        return self.theta_node_coordinates.shape[0]

    @property
    def total_element_number(self) -> int:
        return self.w_location_matrix.shape[1]

    @property
    def total_dof_number(self) -> int:
        """Total degrees of freedom: one w per w-node, then (θ_x, θ_y) pairs per theta-node."""
        return self.total_w_node_number + 2 * self.total_theta_node_number

    def get_geometry_coordinates(self, element_id: int) -> np.ndarray:
        """Return (8, 2) physical coordinates of the Q8 nodes for element_id."""
        node_ids = self.w_location_matrix[:, element_id]
        return self.node_coordinates[node_ids, :]

    def find_w_nodes_on_line(
        self,
        axis: str,
        value: float,
        interval: tuple[float, float] | None = None,
        tolerance: float = 1.0e-10,
    ) -> np.ndarray:
        """
        Return indices of w-nodes whose coordinate along axis equals value (within tolerance).

        Args:
            axis:      "x" or "y".
            value:     Coordinate value to match.
            interval:  Optional (lower, upper) bounds on the perpendicular axis to restrict the search.
            tolerance: Absolute tolerance for coordinate comparison.
        """
        if axis not in {"x", "y"}:
            raise ValueError("axis must be 'x' or 'y'.")

        axis_index = 0 if axis == "x" else 1
        other_axis_index = 1 - axis_index

        mask = np.isclose(self.node_coordinates[:, axis_index], value, atol=tolerance)
        if interval is not None:
            lower, upper = interval
            coordinate = self.node_coordinates[:, other_axis_index]
            mask &= coordinate >= lower - tolerance
            mask &= coordinate <= upper + tolerance

        return np.flatnonzero(mask)
